version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      routine-npm:
        update-types: [minor, patch]
      security-npm:
        applies-to: security-updates
        patterns: ["*"]
        update-types: [minor, patch]
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      routine-actions:
        update-types: [minor, patch]
    open-pull-requests-limit: 10
